name: anomaly-detection-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.3
  - pip:
    - azureml-defaults==1.55.0
    - scikit-learn==1.3.2
    - pandas==2.1.4
    - numpy==1.26.2
    - joblib==1.3.2
    - inference-schema==1.5.1
